apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: service-ing
 namespace: static
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: "dev-static.krishdumpa.com"
   http:
     paths:     
       backend:
         serviceName: k8s-static-svc
         servicePort: 80
